# Generated by Django 2.0 on 2019-09-29 09:35

import Book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类别名称')),
            ],
            options={
                'db_table': 'BookCategory',
            },
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=32, verbose_name='章节名称')),
                ('content', models.TextField(verbose_name='章节内容')),
            ],
            options={
                'db_table': 'BookContent',
            },
        ),
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书籍名字')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('images', models.CharField(max_length=32, verbose_name='书籍封面')),
                ('category', models.ForeignKey(on_delete=Book.models.BookCategory, to='Book.BookCategory')),
            ],
            options={
                'db_table': 'BookName',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=61, verbose_name='用户密码')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
